#!/bin/bash

rm -f server.zip
( cd server; zip -r9 --exclude=\*.svn\* --exclude=\*\~ ../server.zip * >/dev/null 2>&1 )
python2.6 server.zip
unzip -l data.zip
unzip -p data.zip img/metadata.kml | xmllint --format -
